networks:
  oracle-iot-data-poc:
    driver: bridge

services:
  oracle-server:
    container_name: oracledb01
    image: container-registry.oracle.com/database/free:latest
    environment:
      - ORACLE_PWD=password
    volumes:
      - ".:/code"
    networks:
      oracle-iot-data-poc:
        aliases:
          - database
    ports:
        - 1521:1521
